application: freelystats
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets
  
- url: /js
  static_dir: js

- url: /data
  static_dir: data
  mime_type: text

- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: latest
  
builtins:
- remote_api: on